In [2]:
print('Olá mundo')

Olá mundo

In [3]:
import pandas as pd # biblioteca para trabalhar com dados em tabela
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
# criar um DataFrame
data = {
    'nome': ['Rosa', 'Violeta', 'Margarida'],
    'altura_cm': [30, 15, 25],
    'cor': ['vermelho', 'roxo', 'branco']
}
df = pd.DataFrame(data)
df # escrever só df mostra a tabela formatada

        nome  altura_cm       cor
0       Rosa         30  vermelho
1    Violeta         15      roxo
2  Margarida         25    branco

In [5]:
df.shape # (3 /** linhas */, 3 /** colunas */)

(3, 3)

In [6]:
data1 = {
    'cidade': ['Lisboa', 'Porto', 'Braga'],
    'altitude': [2, 85, 190],
    'temperatura': [17.5, 15.2, 14.1]
}
df = pd.DataFrame(data1)
df

   cidade  altitude  temperatura
0  Lisboa         2         17.5
1   Porto        85         15.2
2   Braga       190         14.1

In [7]:
df.shape

(3, 3)

In [8]:
# carregar o iris
iris = datasets.load_iris()

# transformar em DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# iris.data -> contém as medições das flores
# iris.feature_names -> nomes das colunas

df['species'] = iris.target # adicionar a coluna de espécies
# iris.target -> espécie de cada flor

df.head() # primeiras 5 linhas

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
iris = datasets.load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target

In [10]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [11]:
df.shape

(150, 5)

In [12]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species                int64
dtype: object

In [13]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [14]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [15]:
df.columns # anota os nomes das colunas

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [16]:
df['petal length (cm)']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64

In [17]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [18]:
setosa = df[df['species'] == 0]
setosa.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [19]:
virginica = df[df['species'] == 2]
virginica.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
100,6.3,3.3,6.0,2.5,2
101,5.8,2.7,5.1,1.9,2
102,7.1,3.0,5.9,2.1,2
103,6.3,2.9,5.6,1.8,2
104,6.5,3.0,5.8,2.2,2

In [ ]:
# media de petal length da setosa
setosa['petal length (cm)'].mean()

np.float64(1.4620000000000002)

In [21]:
# media de petal length da virginica
virginica['petal length (cm)'].mean()

np.float64(5.5520000000000005)

In [23]:
len(df[df['petal length (cm)'] > 4])

84

In [24]:
df_limpo = df.copy() # copia o iris para não estragar o original
df_limpo.loc[5, 'sepal length (cm)'] = np.nan # meter um NaN na linha 5
df_limpo.loc[10, 'petal width (cm)'] = np.nan # meter um NaN na linha 10

In [25]:
df_limpo.isnull().sum()

sepal length (cm)    1
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     1
species              0
dtype: int64

In [26]:
# preencher com a média
media_sepal = df_limpo['sepal length (cm)'].mean()
media_petal = df_limpo['petal width (cm)'].mean()
df_limpo['sepal length (cm)'].fillna(media_sepal, inplace=True)
df_limpo['petal width (cm)'].fillna(media_petal, inplace=True)

/tmp/ipykernel_1488/1283464071.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_limpo['sepal length (cm)'].fillna(media_sepal, inplace=True)
/tmp/ipykernel_1488/1283464071.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_limpo['petal width (cm)'].fillna(media_petal, inplace=True)

In [27]:
df_limpo.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [28]:
df_sem_species = df.drop('species', axis=1) # remove a coluna species
# axis=1 -> coluna
# axis=0 -> linha

In [29]:
df_sem_species.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [30]:
X = df.drop('species', axis=1) # features
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [31]:
y = df['species']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [32]:
print(X.shape, y.shape)

(150, 4) (150,)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [34]:
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)

In [36]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)
y_pred = modelo.predict(X_test)
print(y_pred[:10]) # mostra as primeiras 10 previsões

[1 0 2 1 1 0 1 2 1 1]

In [ ]:
print(y_test.values[:10]) # mostra os primeiros 10 valores reais

[1 0 2 1 1 0 1 2 1 1]

In [38]:
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc:.2%}')

Accuracy: 100.00%

In [39]:
print(confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [40]:
previsao = modelo.predict([[5.1, 3.5, 1.4, 0.2]])
print(previsao)

[0]

/home/petunia/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [41]:
previsao = modelo.predict([[6.7, 3.1, 5.6, 2.4]])
print(previsao)

[2]

/home/petunia/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [45]:
previsao = modelo.predict([[6.7, 3.1, 5.6, 2.4]])
print(previsao)

[2]

/home/petunia/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(